version: "2"
services:
  php:
    build:
      context: .
    image: 13.235.79.98:8083/repository/php_mysql_app/phpnew_php:56
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DB=moe_db
    volumes:
      - .:/var/www/html/

    ports:
      - "30001:80"
    container_name: moe-php-app
  mysql:
    image: 13.235.79.98:8083/repository/php_mysql_app/mysql:56
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DATABASE=moe_db
    container_name: moe-mysql-app
    volumes:
      - .:/var/www/html/
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
  phpmyadmin:
    image: 13.235.79.98:8083/repository/php_mysql_app/phpmyadmin/phpmyadmin:56
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
